package com.chat.uiview;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

import com.bean.NetworkSegment;
import com.bean.PeerNode;
import com.chat.controll.Manager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ChatsFrame
	 */
	public MainFrame() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		editSendMSgArea = new javax.swing.JEditorPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		receMsgScreenArea = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		peerFriendsTree = new javax.swing.JTree();
		sendMsgBtn = new javax.swing.JButton();
		jMenuBar2 = new javax.swing.JMenuBar();
		shareDirectoryMenu = new javax.swing.JMenu();
		sendFileMenu = new javax.swing.JMenu();
		receFileMenu = new javax.swing.JMenu();
		clearScreen = new javax.swing.JMenu();
		NoticeTagLable = new javax.swing.JLabel();

		popPeerMenu = new JPopupMenu();
		// 增加菜单项到菜单上
		JMenuItem establishPrivConMenuItem = new JMenuItem("发送信息");
		JMenuItem lookShareMenuItem = new JMenuItem("查看共享");
		popPeerMenu.add(establishPrivConMenuItem);
		popPeerMenu.add(lookShareMenuItem);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setViewportView(editSendMSgArea);

		receMsgScreenArea.setColumns(20);
		receMsgScreenArea.setRows(5);
		jScrollPane2.setViewportView(receMsgScreenArea);

		jScrollPane3.setViewportView(peerFriendsTree);

		sendMsgBtn.setText("确认发送");
		sendMsgBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendMsgBtnActionPerformed(evt);
			}
		});

		shareDirectoryMenu.setText("共享目录·");
		shareDirectoryMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				shareDirectoryMenuActionPerformed(evt);
			}
		});
		jMenuBar2.add(shareDirectoryMenu);

		sendFileMenu.setText("发送文件");
		jMenuBar2.add(sendFileMenu);

		receFileMenu.setText("接收文件");
		jMenuBar2.add(receFileMenu);

		clearScreen.setText("清空屏幕");

		NoticeTagLable.setText("群聊、通知消息：");

		establishPrivConMenuItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("单击了发送信息");

				Manager.requestEstablishPrivateConverUIFrame(curToPeerNodeName);

			}
		});
		lookShareMenuItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("单击了查看共享文件;");
			}
		});

		peerFriendsTree.addMouseListener(new MouseListener() {

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				Object obj = peerFriendsTree.getLastSelectedPathComponent();
				if (obj == null)
					return;

				curToPeerNodeName = peerFriendsTree.getLastSelectedPathComponent().toString();
				System.out.println("发生了单击事件" + curToPeerNodeName);
				if (e.getButton() == MouseEvent.BUTTON3) {
					showPopMenu(e.getX(), e.getY());
				}

			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub

			}
		});

		clearScreen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearScreenActionPerformed(evt);
			}
		});
		jMenuBar2.add(clearScreen);
		this.updatePeerNodesTree(NetworkSegment.listPeer);// 更新显示当前peer结点

		setJMenuBar(jMenuBar2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270,
												Short.MAX_VALUE)
										.addComponent(jScrollPane1))
								.addComponent(NoticeTagLable))
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										layout.createSequentialGroup().addComponent(NoticeTagLable).addGap(2, 2, 2)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap())
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
										Short.MAX_VALUE))));

		pack();

	}// </editor-fold>

	private void sendMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void shareDirectoryMenuActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void clearScreenActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void CreateMainFrame(List<PeerNode> peerNodesList) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MainFrame mainFrame = new MainFrame();
				mainFrame.setVisible(true);

				Manager.getInsance().setMainFrame(mainFrame);

			}
		});
	}

	public void updatePeerNodesTree(List<PeerNode> peerNodesList) {

		DefaultMutableTreeNode root = new DefaultMutableTreeNode();
		for (PeerNode peer : peerNodesList) {
			String peerName = peer.getName();
			if (peer.getName().equals(Manager.getInsance().getMePeer().getName())) {
				peerName += "(me)";
			}
			root.add(new DefaultMutableTreeNode(peerName));
		}

		peerFriendsTree.setModel(new DefaultTreeModel(root));
		peerFriendsTree.setRootVisible(false);

	}

	public void showPopMenu(int x, int y) {

		popPeerMenu.show(peerFriendsTree, x, y);

	}

	// Variables declaration - do not modify
	private javax.swing.JLabel NoticeTagLable;
	private JPopupMenu popPeerMenu;
	private javax.swing.JMenu clearScreen;
	private javax.swing.JEditorPane editSendMSgArea;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTree peerFriendsTree;
	private javax.swing.JMenu receFileMenu;
	private javax.swing.JTextArea receMsgScreenArea;
	private javax.swing.JMenu sendFileMenu;
	private javax.swing.JButton sendMsgBtn;
	private javax.swing.JMenu shareDirectoryMenu;
	private String curToPeerNodeName;
	// End of variables declaration
}
