package com.chat.uiview;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import com.bean.NetworkSegment;
import com.bean.PeerNode;
import com.chat.controll.Manager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ChatsFrame
	 */
	public MainFrame() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		NoticeTagLable = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		editSendMSgArea = new javax.swing.JEditorPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		receMsgScreenArea = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		peerFriendsTree = new javax.swing.JTree();
	
		jMenuBar2 = new javax.swing.JMenuBar();
		
		jScrollPane1.setViewportView(editSendMSgArea);
		receMsgScreenArea.setColumns(20);
		receMsgScreenArea.setRows(5);
		receMsgScreenArea.setEditable(false);

		jScrollPane2.setViewportView(receMsgScreenArea);

		jScrollPane3.setViewportView(peerFriendsTree);

		shareFileMenuItem = new javax.swing.JMenuItem();
		sendFileMenuItem = new javax.swing.JMenuItem();
		receiveFileMenuItem = new javax.swing.JMenuItem();
		clearScreenMenuItem = new javax.swing.JMenuItem();

		FileMenu = new JMenu("文件");
		// --------------------
		shareFileMenuItem.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
		shareFileMenuItem.setText("共享文件");
		shareFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				shareFileMenuItemActionPerformed(evt);
			}
		});
		FileMenu.add(shareFileMenuItem);

		sendFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
		sendFileMenuItem.setText("发送文件");
		FileMenu.add(sendFileMenuItem);

		receiveFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
		receiveFileMenuItem.setText("接收文件");
		FileMenu.add(receiveFileMenuItem);

		clearScreenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
		clearScreenMenuItem.setText("清空屏幕");
		FileMenu.add(clearScreenMenuItem);

		jMenuBar2.add(FileMenu);
		setJMenuBar(jMenuBar2);
		// --------------------

		popPeerMenu = new JPopupMenu();
		// 增加菜单项到菜单上
		JMenuItem establishPrivConMenuItem = new JMenuItem("发送信息");
		JMenuItem lookShareMenuItem = new JMenuItem("查看共享");
		popPeerMenu.add(establishPrivConMenuItem);
		popPeerMenu.add(lookShareMenuItem);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		editSendMSgArea.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub
				super.keyTyped(e);

				if (e.getKeyChar() == '\n') {
					String tempContent = editSendMSgArea.getText();
					Manager.getInsance().sendPublicMsg(tempContent);
					editSendMSgArea.setText("");
				}

			}

		});
		
		//-----------------
	
		NoticeTagLable.setText("群聊、通知消息：");

		establishPrivConMenuItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("单击了发送信息");

				Manager.requestEstablishPrivateConverUIFrame(curToPeerNodeName);

			}
		});
		lookShareMenuItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("单击了查看共享文件;");
			}
		});

		peerFriendsTree.addMouseListener(new MouseListener() {

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				Object obj = peerFriendsTree.getLastSelectedPathComponent();
				if (obj == null)
					return;

				curToPeerNodeName = peerFriendsTree.getLastSelectedPathComponent().toString();
				System.out.println("发生了单击事件" + curToPeerNodeName);
				if (e.getButton() == MouseEvent.BUTTON3) {
					showPopMenu(e.getX(), e.getY());
				}

			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub

			}
		});

		this.updatePeerNodesTree(NetworkSegment.listPeer);// 更新显示当前peer结点



		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270,
												Short.MAX_VALUE)
										.addComponent(jScrollPane1))
								.addComponent(NoticeTagLable))
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										layout.createSequentialGroup().addComponent(NoticeTagLable).addGap(2, 2, 2)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap())
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
										Short.MAX_VALUE))));

		pack();

	}// </editor-fold>

	

	private void shareFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser shareFileChooser = new javax.swing.JFileChooser();
		shareFileChooser.setDialogTitle("请选择您共享的目录或文件");
		shareFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		shareFileChooser.setApproveButtonText("确定");
		int result = shareFileChooser.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			File shareFile = shareFileChooser.getSelectedFile();

			System.out.println("共享目录：" + shareFile.getAbsolutePath());

		} else {

		}

	}


	public static void CreateMainFrame(List<PeerNode> peerNodesList) {
		
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MainFrame mainFrame = new MainFrame();
				mainFrame.setVisible(true);

				Manager.getInsance().setMainFrame(mainFrame);

			}
		});
	}

	public void updatePeerNodesTree(List<PeerNode> peerNodesList) {

		DefaultMutableTreeNode root = new DefaultMutableTreeNode();
		for (PeerNode peer : peerNodesList) {
			String peerName = peer.getName();
			if (peer.getName().equals(Manager.getInsance().getMePeer().getName())) {
				peerName += "(me)";
			}
			root.add(new DefaultMutableTreeNode(peerName));
		}

		peerFriendsTree.setModel(new DefaultTreeModel(root));
		peerFriendsTree.setRootVisible(false);

	}

	public void showPopMenu(int x, int y) {

		popPeerMenu.show(peerFriendsTree, x, y);

	}

	public void showReceiveMsg(String msgContent) {
		// TODO Auto-generated method stub

		receMsgScreenArea.append(msgContent);

	}


	private javax.swing.JLabel NoticeTagLable;
	private JPopupMenu popPeerMenu;
	private javax.swing.JEditorPane editSendMSgArea;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTree peerFriendsTree;
	private javax.swing.JTextArea receMsgScreenArea;
	private javax.swing.JMenu FileMenu;
	private String curToPeerNodeName;
	private javax.swing.JMenuItem clearScreenMenuItem;
	private javax.swing.JMenuItem receiveFileMenuItem;
	private javax.swing.JMenuItem sendFileMenuItem;
	private javax.swing.JMenuItem shareFileMenuItem;
	
}
